name: update readme with RSS feed

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Public IP
        id: ip
        run: |
          result=$(curl https://ipinfo.io/json)
          ip=$(echo $result | jq -r '.ip')
          echo "::set-output name=public_ip::$ip"

      - name: Use Public IP
        run: |
          echo "The public IP is ${{ steps.ip.outputs.public_ip }}"

      - name: Make CF API request and extract Rules ID
        id: extract_id
        run: |
          ipv4=${{ steps.ip.outputs.public_ip }}    
          response=$(curl --request POST \
            --url https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/firewall/access_rules/rules \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.CF_API_KEY }}' \
            --data '{"mode":"whitelist","configuration":{"target":"ip","value":"'"$ipv4"'"},"notes":"Github Action IP for API ACCESS"}')
          echo "Response: $response"
          id=$(echo $response | jq -r '.result.id')
          echo "Extracted ID: $id"
          echo "ID=$id" >> $GITHUB_ENV

      - name: Update README with RSS feed
        uses: xiaotianxt/rss-to-readme@main
        with:
          feed-url: https://xiaotian.dev/index.xml
          token: ${{ secrets.token }}
