name: update readme with RSS feed

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: xiaotianxt/rss-to-readme@main
      with:
        feed-url: https://xiaotian.dev/index.xml
        token: ${{ secrets.token }}
