name: update readme with RSS feed

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: JasonEtco/rss-to-readme@v1
      with:
        feed-url: https://xiaotian.dev/index.xml
        readme-section: 'feed'
        empty-commits: false
        template: "> {{ excerpt }}\n\n[Read more!]({{ url }})"
