name: update readme with RSS feed

on:
  # schedule:
    # - cron: "0 8 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # allows to trigger by some other repo
  repository_dispatch:
    types: [rss-update]

  
  # run on every push on the master branch
  # push:
    # branches:
    # - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bypass Cloudflare for GitHub Action
        uses: xiaotianxt/bypass-cloudflare-for-github-action@19dd5c383f68ada79c32a5e9c509c9bdd5aa3ea5
        with:
          cf_zone_id: ${{ secrets.CF_ZONE_ID }}
          cf_api_token: ${{ secrets.CF_API_TOKEN }}

      - name: Update README with RSS feed
        uses: xiaotianxt/rss-to-readme@main
        with:
          feed-url: https://xiaotian.dev/index.xml
          token: ${{ secrets.TOKEN }}
